base_url: /
domain:
title: New Coder
subtitle: five life jackets to throw to the new coder
posts_url: /<title>/
author: Lynn Root
description: Five Life Jackets to Throw to the New Coder - Python tutorials

analytics:
feed: false
social:
    github: econchick
    twitter: roguelynn

archive_layout: archive.html
archives_url: /archives/
jinja:
    extensions:
        - jinja2.ext.loopcontrols
tag_layout: tag.html
tags_url: /tags/
